# Generated by Django 3.2.3 on 2021-08-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('storename', models.CharField(max_length=50)),
                ('totalbooks', models.IntegerField(default=1)),
                ('storeimage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'storeinfo',
            },
        ),
    ]
