# Generated by Django 3.2.3 on 2021-08-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeowner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='totalbooks',
            field=models.IntegerField(default=0),
        ),
    ]
