# Generated by Django 3.2.3 on 2021-08-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeowner', '0002_auto_20210827_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='first_name',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='last_name',
            field=models.CharField(default='xyz', max_length=50),
        ),
    ]
